# Generated by Django 5.1.5 on 2025-01-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_configdice_created_at_configindeed_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdice',
            options={'verbose_name': 'Dice Config', 'verbose_name_plural': 'Dice Configs'},
        ),
        migrations.AlterModelOptions(
            name='configindeed',
            options={'verbose_name': 'Indeed Configs', 'verbose_name_plural': 'Indeed Configs'},
        ),
        migrations.AlterModelOptions(
            name='configlinkedin',
            options={'verbose_name': 'LinkedIn Config', 'verbose_name_plural': 'LinkedIn Configs'},
        ),
        migrations.AlterModelOptions(
            name='configziprecruiter',
            options={'verbose_name': 'ZipRecruiter Config', 'verbose_name_plural': 'ZipRecruiter Configs'},
        ),
        migrations.AddField(
            model_name='configziprecruiter',
            name='done_today',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='configziprecruiter',
            name='meta_data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='configziprecruiter',
            name='run_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configziprecruiter',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
