# Generated by Django 5.1.5 on 2025-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_alter_configdice_options_alter_configindeed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboardscrapehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='configziprecruiter',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='configziprecruiter',
            name='run_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configziprecruiter',
            name='status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardscrapehistory',
            name='date_scrape_started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardscrapehistory',
            name='raw_json_passed_to_scraper',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardscrapehistory',
            name='raw_json_response_from_apify',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
