# Generated by Django 5.1.5 on 2025-01-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0004_jobboardscrapehistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configziprecruiter',
            name='run_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configziprecruiter',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
