# Generated by Django 5.1.5 on 2025-01-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0005_alter_configziprecruiter_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboardscraperesults',
            name='job_board_scrape_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapping.jobboardscrapehistory'),
        ),
    ]
