# Generated by Django 5.1.5 on 2025-01-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0006_jobboardscraperesults_job_board_scrape_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobboardscrapehistory',
            options={'verbose_name': 'Scrape History', 'verbose_name_plural': 'Scrapes History'},
        ),
        migrations.AlterModelOptions(
            name='jobboardscraperesults',
            options={'verbose_name': 'Scrape Result', 'verbose_name_plural': 'Scrape Results'},
        ),
    ]
