# Generated by Django 5.1.5 on 2025-01-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0007_alter_jobboardscrapehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobboardscraperesults',
            name='date_inserted',
        ),
        migrations.AddField(
            model_name='jobboardscraperesults',
            name='raw_json_job_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='jobboardscraperesults',
            name='raw_json_result',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardscrapehistory',
            name='run_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobboardscrapehistory',
            name='scraper_name',
            field=models.CharField(default='apply-jobs-forever', max_length=255, null=True),
        ),
    ]
