# Generated by Django 5.1.5 on 2025-01-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0008_remove_jobboardscraperesults_date_inserted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboardscraperesults',
            name='date_job_posted_human_form',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
