# Generated by Django 5.1.5 on 2025-01-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0009_jobboardscraperesults_date_job_posted_human_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboardscraperesults',
            name='salary_human_readable_form',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
